version:  '3.6'

services:  

 # Redis database 

  redis:
    image: redis
    ports:
      - "6379:6379"


  # PostgresSQL
  postgres:
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password 
      POSTGRES_URI: postgres://admin:password@localhost:5432/smart-brain-docker
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"


  # Backend API
  smart-brain-api:
    container_name: backend
    build: ./ 
    volumes:
      - ./:/user/src/smart-brain-api 
    command: npm start 
    working_dir: /user/src/smart-brain-api
    ports:
      - "3000:3000"
    environment: 
      POSTGRES_URI: postgres://admin:password@postgres:5432/smart-brain-docker
      Redis_URI: redis://redis:6379
    links:
      - postgres
      - redis
   
  
  













